[package]
name = "ui_demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3.0"
iced_futures = "0.3.0"
async-std = { version = "1.10.0", features = ["unstable"]}